---
    kind: pipeline
    type: docker
    name: default
    
    - name: test
      image: node
      commands:
      - npm install
      - npm install -g "@angular/cli" --silent
      - npm run test