export { HttpClientModule } from '@angular/common/http';
export { NgModule } from '@angular/core';
export { ReactiveFormsModule } from '@angular/forms';
export { MatButtonModule } from '@angular/material/button';
export { MatExpansionModule } from '@angular/material/expansion';
export { MatInputModule } from '@angular/material/input';
export { MatSidenavModule } from '@angular/material/sidenav';
export { MatToolbarModule } from '@angular/material/toolbar';
export { BrowserModule } from '@angular/platform-browser';
export { BrowserAnimationsModule } from '@angular/platform-browser/animations';
export { RouterModule, Routes } from '@angular/router';
export { AppComponent } from './app.component';
export { DashboardComponent } from './Components/dashboard/dashboard.component';
export { HeaderComponent } from './Components/header/header.component';
export { HomeComponent } from './components/home/home.component';
export { LoginFormComponent } from './Components/login-form/login-form.component';
export { MealsComponent } from './components/meals/meals.component';
export { PageNotFoundComponent } from './Components/page-not-found/page-not-found.component';
export { RegisterFormComponent } from './Components/register-form/register-form.component';
export { TopNotificationComponent } from './components/top-notification/top-notification.component';
export { MatTableModule } from '@angular/material/table';

